// Copies ABIs from Foundry build output into typed TS modules (run after `forge build`).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
const dest = join(here, "..", "src", "abi");
mkdirSync(dest, { recursive: true });

const contracts = {
  payrollFactoryAbi: "PayrollFactory.sol/PayrollFactory.json",
  payrollAbi: "Payroll.sol/Payroll.json",
  sliceRouterAbi: "SliceRouter.sol/SliceRouter.json",
  batchConverterAbi: "BatchConverter.sol/BatchConverter.json",
  bonusVestingAbi: "BonusVesting.sol/BonusVesting.json",
  marketClockAbi: "MarketClock.sol/MarketClock.json",
  oracleAdapterAbi: "OracleAdapter.sol/OracleAdapter.json",
  projectTokenHooksAbi: "ProjectTokenHooks.sol/ProjectTokenHooks.json",
  feeCollectorAbi: "FeeCollector.sol/FeeCollector.json",
};

let index = "// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit\n";
for (const [name, file] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(join(out, file), "utf8"));
  writeFileSync(join(dest, `${name}.ts`), `// AUTO-GENERATED — do not edit\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`);
  index += `export { ${name} } from "./${name}";\n`;
}
writeFileSync(join(dest, "index.ts"), index + 'export { erc20Abi } from "viem";\n');
console.log(`Synced ${Object.keys(contracts).length} ABIs to ${dest}`);
